-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: 414cfa7b2322cf1c46cd33a49e9da833ad785473
    hooks:
    -   id: check-added-large-files
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/Harwood/pre-commit-hooks
    sha: f756b8e65f851891e4f4cfc170a072ea854e4e97
    hooks:
    -   id: update-travis-ci
        args:
        - --user=Harwood
        - --repo=Chronos
        - --travis=travis-ci.org
